### ISSUE TITLE
1_getting_Started.pnby NAmeError: name 'DummyVecEnv' is not defined

### ISSUE THREAD

**Issue by orkuntanik** [araffin/rl-tutorial-jnrr19#8]
After manually including the line:

from stable_baselines.common.vec_env.dummy_vec_env import DummyVecEnv

visualize trained agent section now throws:

AttributeError: 'CartPoleEnv' object has no attribute 'num_envs'

**Comment by araffin** [comment]
Hello,
thanks for reporting the issues, both should be fixed now ;)

**Comment by orkuntanik** [comment]
I should thank you for the great work with stable baselines... Also the lightning quick response :)
